### ISSUE TITLE
Bug/PNJ Hostile "Sabre de nuit Galeux"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#101]
Zone : Sombrevallon
**Décrivez le bug**
Le pnj bête Hostile indiqué en rouge ne nous attaque pas comme il devrait le faire mais agis comme un pnj neutre dans toute la zone.

**Comportement attendu**
Qu'il nous attaque quand on passe a côté 

**Capture d'écran**
![WoWScrnShot_021020_193748](https://user-images.githubusercontent.com/60512757/74178998-d85ddc00-4c3c-11ea-91b7-47a72bd662b6.jpg)

**Systèmes (veuillez compléter les informations suivantes):**
OS: [e.g. Windows 10]
PatchChecked: patch20200205
GoodPatch: Inconnu au bataillon
FixDB: ???
Version 7765a35

**Comment by buddyqc69** [comment]
Il serait apprécié d'avoir un liens wowhead du PNJ concerné s.v.p, merci ^^

**Comment by Nohor** [comment]
voila ! https://fr.classic.wowhead.com/npc=2032/sabre-de-nuit-galeux

**Comment by buddyqc69** [comment]
résolu lors du prochain reboot
