### ISSUE TITLE
arme pro DH 

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#16]
niveaux 100 
 
https://fr.wowhead.com/quest=41120/petits-accords 

le pnj n'est pas devant le DJ

**Comment by Lyhannor** [comment]
le pnj  n'est toujour pas la

**Comment by buddyqc69** [comment]
Il est supposé être dedans pour donjon

**Comment by Lyhannor** [comment]
non selon la quete il et devant le dj pour pouvoir acces a la zone
