### ISSUE TITLE
le pnj n'a pas la pour aller a haut roc

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#17]
niveaux 100 
 
https://fr.wowhead.com/quest=39733/le-mont-solitaire

le pnj n'est pas a l’Aire de Krasus,

**Comment by buddyqc69** [comment]
Pourrais-tu vérifié ? j'ai ajouté le PNJ manquant, merci !

**Comment by Lyhannor** [comment]
c'est bon il et la
