### ISSUE TITLE
DH Donjon 

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#18]
un possible de rentre dans le donjon 

https://fr.wowhead.com/violet-hold

**Comment by Lyhannor** [comment]
pour pouvoir faire la quete  

https://fr.wowhead.com/quest=41120/petits-accords

**Comment by buddyqc69** [comment]
il faut donc que le pnj sois a l'extérieur car sinon tu peux pas rentrer dans le donjon?

**Comment by Lyhannor** [comment]
oui

**Comment by Lyhannor** [comment]
car on lui promait de pas faire de connerie dans le dj car on n'est pas le droit d'aller dedans de base ^^

**Comment by buddyqc69** [comment]
d'accord je vais regler cela drakking666 tu pourrais aller rajouter le pnj manquant? svp

**Comment by buddyqc69** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/46275063/72757068-ff287580-3b9c-11ea-8e1b-d5cc17025d1c.png)

je l'ai mis à droite de l'entrée ^^
