### ISSUE TITLE
Quêtes: La combe de hurlements 

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#24]
les totem ne peuveut etre taper mais eu peuvnet nous taper 

https://fr.wowhead.com/quest=40316/la-combe-des-hurlements

**Comment by buddyqc69** [comment]
il ne semble pas avoir de bug avec cette quêtes? j'ai complété la quêtes sans même un problème, pouvez vous expliquer qu'elle étais le problème ?
