### ISSUE TITLE
{WIP} Quêtes: la prochaine génération {zone haut roc}

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#28]
impossible d'ouvrit l'oeuf de broubie

https://fr.wowhead.com/quest=40102/murlocs-la-prochaine-g%C3%A9n%C3%A9ration

**Comment by buddyqc69** [comment]
La quêtes peut s'effectuer mais il manque certaines chose dans la quêtes mais elle peut être complété!

- [x] ajouté la section requise sur l'oeuf effectué
- [ ] ajouté la vehicule murloc avec les spell
- [ ] vérifié la quêtes et la valider.

la quêtes peux être effectué et valider.
