### ISSUE TITLE
[WIP] Quêtes: acqui ou inné {zone haut roc}

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#29]
impossible de parler au tétard 

https://fr.wowhead.com/quest=40045/acquis-ou-inn%C3%A9

**Comment by Lyhannor** [comment]
qunad j'ia voulut leur parler je n'est pas put

**Comment by buddyqc69** [comment]
Nous pouvons maintenant parler au créature, il me reste juste à ajouter le texte à chaque tu leur parle et qu'il se mette a courrir partout surement ^^

**Comment by buddyqc69** [comment]
le quête peut etre résolu
