### ISSUE TITLE
Profession: Couture *Ne fonctionne pas*

### ISSUE THREAD

**Issue by billtorreno** [buddyqc69/infernalwowproject#3]
**Description:**

Description du problème ici.
après avoir appris la compétence, je veux améliorer la compétence sur les objets de couture mais ne fonctionne pas, coincé à 0/0

**Dites-nous ce qui se passe.**
rien, coincé à 0/0

**Dites-nous ce qui devrait arriver à la place.**
Nous pouvons crée des objects avec la profession mais le niveau ne semble pas monter de la compétence.

**Étapes pour reproduire le problème:**

1. Apprendre couture https://www.wowhead.com/tailoring
2. Crée des objets disponible de base
3. Cela ne monte pas le niveau de la profession

**Branch(es):**
8.2.5 32750 frFR

**Comment by buddyqc69** [comment]
Il faut se déconnecter et se reconnecter et ca devrait fonctionner sans problème, pour le moment.
Nous allons tenter de corriger ce problème qu'il peut arriver après avoir appris le métiers.

**Comment by buddyqc69** [comment]
D'accord

Le 31 déc. 2019 8:38 p.m., billtorreno <notifications@github.com> a écrit :

Description:

Description du problème ici.
après avoir appris la compétence, je veux améliorer la compétence sur les objets d'artisanat mais ne fonctionne pas, coincé à 0/0

Dites-nous ce qui se passe.
rien, coincé à 0/0

Dites-nous ce qui devrait arriver à la place.
Nous pouvons crée des objects avec la profession mais le niveau ne semble pas monter de la compétence.

Étapes pour reproduire le problème:

  1.  learn skill 197 ou 264617 https://www.wowhead.com/tailoring
  2.  Crée des objets disponible de base
  3.  Cela ne monte pas le niveau de la profession

Branch(es):
8.2.5 32750 frFR

**Comment by buddyqc69** [comment]
a venir
