### ISSUE TITLE
probleme de texture  {zone haut roc}

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#30]
![WoWScrnShot_012120_145220](https://user-images.githubusercontent.com/60049315/72810369-b5ec2a80-3c5d-11ea-852d-65d4865568d8.jpg)

le volatile devrait etre sur une sorte de totem

**Comment by buddyqc69** [comment]
ils sont sur un perche pour le moment, je vais tenté d'avoir le ID exacte du totems etc.. et le règler futurement ^^ merci

**Comment by buddyqc69** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/46275063/72836651-0f068f00-3c5b-11ea-95da-76106b8663bc.png)

**Comment by Lyhannor** [comment]
tu et bon

**Comment by Lyhannor** [comment]
c'est la meme chose que office xD

**Comment by buddyqc69** [comment]
Merci, merci ^^
