### ISSUE TITLE
bug quete coeur de chasseur {zone haut roc}

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#31]
impossible de parler a Addie quand on lui click dessus rien de se passe 

https://fr.wowhead.com/quest=40216/c%C5%93ur-de-chasseur

![WoWScrnShot_012120_145846](https://user-images.githubusercontent.com/60049315/72810772-88ec4780-3c5e-11ea-98b1-b6423fcbb9b2.jpg)

**Comment by buddyqc69** [comment]
il est supposer faire quoi exactement ?

**Comment by Lyhannor** [comment]
tu et semser pouvoir lui parler de la chasse pour qu'elle finise la quete

**Comment by buddyqc69** [comment]
ah oki donc elle valide la quête? ^^ loll

**Comment by Lyhannor** [comment]
oui

**Comment by Lyhannor** [comment]
mais impossible d'aovir la ligne de dialogue avec elle

**Comment by buddyqc69** [comment]
je vérifie cela dans pas long ^^

**Comment by Lyhannor** [comment]
tkt tu a le temps pour cela

**Comment by Lyhannor** [comment]
sa commence a etre dur de quete sans heal et des sort en moin ^^

**Comment by buddyqc69** [comment]
ca dis que tu dois valider la quête avec ce PNJ sur wowhead.
https://fr.wowhead.com/npc=94409/hemet-nesingwary

Peux tu confirmé ?

**Comment by Lyhannor** [comment]
je ne peut pas pour le moment il faut que je parle a la dame sur la capture

**Comment by buddyqc69** [comment]
ah d'accord tu est au début de la quête ?

**Comment by Lyhannor** [comment]
oui avant je devait tuer une chevre pour quel me donne un livre

**Comment by buddyqc69** [comment]
il faut juste lui parler, elle ne donne aucune quête ? car sur wowhead je ne voie aucune informations sur elle ^^

**Comment by Lyhannor** [comment]
bas tout se que je sait c'est qu'il fiat lui parler j'ia jamais fait cette avant ^^

**Comment by buddyqc69** [comment]
je travail sur sont action ^^

**Comment by Lyhannor** [comment]
ok

**Comment by buddyqc69** [comment]
J'ai appliquer un fix, peux tu vérifier ? s.v.p

**Comment by Lyhannor** [comment]
ok

**Comment by Lyhannor** [comment]
je suisen fly pour y aller

**Comment by Lyhannor** [comment]
![WoWScrnShot_012120_190757](https://user-images.githubusercontent.com/60049315/72830600-5869d500-3c81-11ea-8220-2d690c8708e7.jpg)

**Comment by buddyqc69** [comment]
Résolu et testé, résolu !! :)
