### ISSUE TITLE
Pnj au mauvais texte

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#51]
Serveur: 8.2.5
Zone : Clairière de Tirisfall : Ferme de solliden
Les fermiers en plein airs dans un champs de potirons nous gueules des "dégagez de ma cuisine".
J'ai beau regarder...pas d'cuisine en vue

![WoWScrnShot_013120_171421](https://user-images.githubusercontent.com/60512757/73555194-6e2f8500-444d-11ea-9bb0-c44f746c17f0.jpg)

**Comment by buddyqc69** [comment]
Pouvez-vous confirmé si le problème à été résolu ? merci
