### ISSUE TITLE
{WIP} Bug/Quête Gobelins

### ISSUE THREAD

**Issue by Ryarru** [buddyqc69/infernalwowproject#52]
Zone :  Quartier Générale de la SCK
Quête : Membre d'honneur 
Lien : https://fr.wowhead.com/quest=14113/membre-dhonneur

Dans cette quête le joueur doit revêtir des accessoires festifs et divertir des pnj , les accessoires ne sont pas disponibles de même que les pnj à divertir autours de la piscine sont absent.

**Comment by buddyqc69** [comment]
note à moi même: il manque le smart script lorsque qu'il envoi ce spell (quand le menu ouvre..) chaque items devrait faire accomplir une étape de la quête et ensuite spécifiquement écrire le texte selon l'action.

**Comment by buddyqc69** [comment]
ca sera résolu sous peu, merci !
