### ISSUE TITLE
Bug/Quete Undead "Pas mieux que les zombies"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#53]
A cette quete il faut simplement aller parler a  Darnell
Hors quand on clique sur "terminer la quete" rien ne se passe et la quete ne s'accomplie pas du coup.
https://fr.wowhead.com/quest=24970/pas-mieux-que-les-zombies

![WoWScrnShot_020120_135058](https://user-images.githubusercontent.com/60512757/73592393-2ca8e380-44fa-11ea-9ffc-43ebc2b56bd9.jpg)

**Comment by buddyqc69** [comment]
Il est surement juste pas au courant qui doit te valider une quête 🤣 ta pogne tu? Lool

**Comment by buddyqc69** [comment]
résolu
