### ISSUE TITLE
Bug/Quête Humains " Même pas peur "

### ISSUE THREAD

**Issue by Ryarru** [buddyqc69/infernalwowproject#60]
Zone : Vallée de Comté du Nord
Lien : https://fr.wowhead.com/quest=28809/m%C3%AAme-pas-peur

Le joueur est censé ramener a la vie/soigner les soldats au sol mais aucunes actions possible ici.

**Comment by buddyqc69** [comment]
Pouvez-vous vérifié si cela fonctionne, merci
