### ISSUE TITLE
Bug/Quete Elfe de la nuit "Les pousses de Sylvain"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#61]
A cette quete on doit ramasser des "pousses de sylvain" au sol. Hors une zone entourant la tente du pnjpossède des pousses non cliquables et non en surbrillance, inutilisable donc.
https://fr.classic.wowhead.com/quest=919/les-pousses-de-sylvain

![WoWScrnShot_020220_104553](https://user-images.githubusercontent.com/60512757/73606345-7997c300-45a9-11ea-9e75-07ae5a010d38.jpg)

**Comment by buddyqc69** [comment]
Pouvez-vous vérifié si cela fonctionne, merci
