### ISSUE TITLE
Bug/ Spell Druide Sous forme felin "Morsure Feroce"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#62]
Cette technique ne semble pas fonctionner et indique "cible incorrecte" quelque soit la cible que l'on attaque
https://fr.classic.wowhead.com/spell=22568/morsure-f%C3%A9roce

**Comment by buddyqc69** [comment]
Pouvez-vous vérifié si cela fonctionne, merci
