### ISSUE TITLE
Bug/Quete elfe de la nuit "Capturereve d'emeraude"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#63]
Dans cette quête on doit aller a une maisonnette et cliquer sur une commode pour récupérer le dit "capturereve d’émeraude" Hors il est incliquable.

https://fr.classic.wowhead.com/quest=2438/le-captur%C3%AAve-d%C3%A9meraude

![WoWScrnShot_020220_110102](https://user-images.githubusercontent.com/60512757/73606545-acdb5180-45ab-11ea-94a8-fbd2032d070d.jpg)

**Comment by buddyqc69** [comment]
Pouvez-vous vérifié si cela fonctionne, merci
