### ISSUE TITLE
Bug/Pierre de foyer Humains

### ISSUE THREAD

**Issue by Ryarru** [buddyqc69/infernalwowproject#64]
Zone : Auberge de la Fierté du Lion/Comté de l'Or
PNJ : https://fr.classic.wowhead.com/npc=295/aubergiste-farley

Lorsque nous arrivons en tant qu'humain à l'Auberge de la Fierté du Lion à Comté-de-l'Or  il est impossible de faire de cette auberge notre foyer.

**Comment by buddyqc69** [comment]
Pouvez-vous vérifié si cela fonctionne, merci
