### ISSUE TITLE
Bug/ Quete "Bigobox 413"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#66]
Dans cette quete il faut chopper 4 char de clampant. hors j'en ai tué 10, tous impossible a fouiller. le corps n'est pas en surbrillance ni rien il ne propose pas de fouille.
https://fr.wowhead.com/quest=13521/bigobox-413

![WoWScrnShot_020220_200750](https://user-images.githubusercontent.com/60512757/73613622-05d0d700-45f8-11ea-9e56-4ce2ab028536.jpg)

**Comment by buddyqc69** [comment]
Pouvez-vous vérifié si cela fonctionne, merci
