### ISSUE TITLE
Bug/Quete Worgen "Quelque chose ne va pas"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#68]
Impossible de rendre la quete, le pnj ne semble pas se sentir concerné. 
((PS: il s'agit de la 2nd quete sans ça pas moyen d'avancer))

https://fr.wowhead.com/quest=14091/quelque-chose-ne-va-pas

![WoWScrnShot_020220_220206](https://user-images.githubusercontent.com/60512757/73615389-ac70a400-4607-11ea-9ea4-6953e450153a.jpg)

**Comment by buddyqc69** [comment]
Besoin de vérification, merci
