### ISSUE TITLE
Bug/ Pnj Gnome "Carvo Boumboulon"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#69]
Simple souci d'apparence il ne tient pas d'arme ce qui rend la pause ridicule
https://fr.wowhead.com/npc=47250/carvo-boumboulon

![WoWScrnShot_020220_221930](https://user-images.githubusercontent.com/60512757/73615654-3588da80-460a-11ea-804c-172a57f9cc6f.jpg)

**Comment by buddyqc69** [comment]
Pouvez-vous vérifié si cela est encore d'actualité ? nous avons appliquer un fix, merci
