### ISSUE TITLE
[WIP] Quete Donjon de ragefeu

### ISSUE THREAD

**Issue by Drakking666** [buddyqc69/infernalwowproject#7]
La quete "Tous les Orcs présents à l'appel", les NPCs "61680" n'est pas sélectionnable ducoup on ne peux faire la quete

**Comment by buddyqc69** [comment]
Nous allons résoudre le problème ce soir, merci !

**Comment by buddyqc69** [comment]
Correction en cours:
[-] ajout de l'option de créature de discuter avec le joueurs.
[] faire en sorte que le quêtes se valide

**Comment by buddyqc69** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/46275063/72652179-af0aa280-3953-11ea-8e3d-108d26d8e9ad.png)

l'objectif de la quêtes c'est de parler au PNJ pour le sauver et il ne le fesait pasl.

Pouvez-vous confirmé la résolu ?

**Comment by buddyqc69** [comment]
dans template de la créature (npc_flag) étais ajouter celui que le npc ne peux pas être selectionner.

33554432 | 0x0200 0000 | UNIT_FLAG_NOT_SELECTABLE | Can't be selected by mouse or with /target

**Comment by buddyqc69** [comment]
comme la quête le réveil NPC 66167

**Comment by buddyqc69** [comment]
ajouté npcflag à 3 et ont peux maintenant parler au NPC
