### ISSUE TITLE
Bug/Quete Gnome "Decontamination"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#71]
Le processus de décontamination bug, une fois que l'on clique sur la machine celle ci ne fait rien, elle nous attrape mais ne bouge plus
https://fr.wowhead.com/quest=27635/d%C3%A9contamination

![WoWScrnShot_020220_222452](https://user-images.githubusercontent.com/60512757/73615721-daa3b300-460a-11ea-8091-b2c6a4a900f1.jpg)

**Comment by buddyqc69** [comment]
doit être vérifié svp, merci
