### ISSUE TITLE
Bug / Pnj/Loot "Envahisseur dos Hirsute"

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#72]
On a beau en tuer autant que l'on veut, ces creatures que l'on trouve dans la zone depart des Taurens ne lachent pas du tout de loot, et ne sont pas en surbrillance non plus a leur mort.

https://fr.wowhead.com/npc=36943/envahisseur-dos-hirsute

![WoWScrnShot_020220_223908](https://user-images.githubusercontent.com/60512757/73615922-29eae300-460d-11ea-958d-e434e1cec1d8.jpg)

**Comment by buddyqc69** [comment]
Pouvez-vous vérifié, nous avions appliquer un fix pour ce problème, veuillez vérifier svp merci
