### ISSUE TITLE
Bug/ PNJ ?  Kyle le Frenetique x3

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#74]
Zone: Sabot de Sang
Il se trouve un Kyle le Frenetique seul mais aussi un autre groupe de trois Kyles qui se court après.
 
![WoWScrnShot_020220_230457](https://user-images.githubusercontent.com/60512757/73616179-8ef40800-4610-11ea-8bd8-fc8b2cab5f3c.jpg)

**Comment by buddyqc69** [comment]
surement un problème de factions je verifie cela merci

**Comment by Nohor** [comment]
ça a l'air resolu !
