### ISSUE TITLE
Quêtes : L'arène de sang : l'ultime défi

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#8]
niveaux 65 l'arène de sang quand on tue le pnj sela ne compte pas pour la quete 

https://fr.wowhead.com/quest=9977/lar%C3%A8ne-de-sang-lultime-d%C3%A9fi

**Comment by buddyqc69** [comment]
GUID:317212
ENTRY:18069

**Comment by buddyqc69** [comment]
nous travaillons la dessu, merci

**Comment by buddyqc69** [comment]
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(18069, 0, 14, 0, 6, 0, 100, 1, 0, 0, 0, 0, 15, 9977, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 'Mogor - On Death - Give Quest Credit');

problème résolu
