### ISSUE TITLE
Bug/PNJ Monture Dent de Sabre (Achat de monture)

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#83]
On peut apprendre la competence de monte mais pas acheter une monture.
https://fr.wowhead.com/npc=4730/lelanai

![WoWScrnShot_020520_120044](https://user-images.githubusercontent.com/60512757/73836317-448caa00-480f-11ea-8dea-091239ca70e0.jpg)

**TO DO LIST:**
- [x] vérifié et confirmé par @buddyqc69 
- [x] ajouté npcflag=131 sur le PNJ concerné
- [ ] vérifié par Nohor et confirmé qu'il fonctionne
**Si vérifié et fonctionnel juste cliquer sur le petit crochet pour valider, merci**

**Comment by buddyqc69** [comment]
ce sera bientôt résolu merci

**Comment by buddyqc69** [comment]
correction apporté, pouvez-vous vérifier s.v.p merci

**Comment by buddyqc69** [comment]
https://github.com/buddyqc69/infernalwowproject/blob/master/patch20200205

**Comment by buddyqc69** [comment]
7765a35eab75e145383870d3b2294c56a26bd500

**Comment by Nohor** [comment]
souci resolu
