### ISSUE TITLE
Bug d'affichage a Hurlevent

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#85]
Il semble manquer un sole t des pnj pour les feux d'artifice, chose qui s'affiche correctement a darnassus

![WoWScrnShot_020520_123136](https://user-images.githubusercontent.com/60512757/73838308-b5ce5c00-4813-11ea-8888-e0d88ff7910b.jpg)

**Comment by buddyqc69** [comment]
peux tu supprimer ton dossier "cache" dans le dossier de ton jeu merci ^^

**Comment by Nohor** [comment]
C'est chose faite ! mais cela ne change rien on ne vois toujours que les paquets qui flottes !

**Comment by buddyqc69** [comment]
Qu'est qui est supposer etre la?

**Comment by Nohor** [comment]
dans les autres ville ya comme un stand de feux d'artifice avec un vendeur ocmme a Darnassus, la faction du cercle cenarien askip. ya des quetes en rapport etc. j'pense qu'il manque l'estrade + pnj + vendeur de feux d'artifice

**Comment by buddyqc69** [comment]
Pourrais-tu nous envoyer une photo de les autres endroits s.v.p ? merci
