### ISSUE TITLE
Bug/Dialogue Rochenoire (drôle)

### ISSUE THREAD

**Issue by Ryarru** [buddyqc69/infernalwowproject#86]
Petit bug de script dialogue amusant , les orcs roches noirs disent " Les raisins étaient délicieux" en mourant je doute qu'il s'agisse de leur réplique initiales.

**Comment by buddyqc69** [comment]
Manque d'informations, pouvez-vous mettre un liens vers une video sur wowhead ou youtube montrant ce qui se passe dans la quêtes, ou un liens wowhead vers la quêtes, manque la version aussi.
Merci

**Comment by buddyqc69** [comment]
ce n'est pas un bug
