### ISSUE TITLE
Bug/ Pnj x2

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#89]
Version:  7765a35eab75e145383870d3b2294c56a26bd500

Ces deux Pnj se suivent dans Darnassus

https://fr.classic.wowhead.com/npc=4167/dendrythis

![WoWScrnShot_020520_215844](https://user-images.githubusercontent.com/60512757/73883077-919a6b80-4863-11ea-84f7-6a2848614774.jpg)

**Comment by buddyqc69** [comment]
résolu, sera réglé lors du prochain reboot, merci
https://github.com/buddyqc69/infernalwowproject/commit/92fd93adfd98c2084d6dd4f9913b3e61346f76c2
