### ISSUE TITLE
Bug?/ Druid Feral

### ISSUE THREAD

**Issue by Nohor** [buddyqc69/infernalwowproject#90]
Version : 7765a35eab75e145383870d3b2294c56a26bd500
Patch20200205
La capacité de transformation en forme aquatique apparaît comme un passif :o
(j'ignore si c'et ce qu'il est bel et bien devenu depuis la 8.0.1 j'ai un doute)

![WoWScrnShot_020520_224438](https://user-images.githubusercontent.com/60512757/73886170-5a2ebd80-4869-11ea-890c-14ea684a3071.jpg)

**Comment by buddyqc69** [comment]
L'avez vous tester sous l'eau?

**Comment by buddyqc69** [comment]
https://fr.wowhead.com/spell=276012/forme-aquatique

Ce n'est pas un bug merci
