### ISSUE TITLE
bug de ramassege de mod 

### ISSUE THREAD

**Issue by Lyhannor** [buddyqc69/infernalwowproject#99]
quand l'on ramasse des personnage cale fonctoinne avec tout les mod 

pour reproduire se bug il faut juste tuer des ennemie les rammaser

ne pas avoir un message d'eurre nous empéchant de les ramaser 

![WoWScrnShot_021020_144738](https://user-images.githubusercontent.com/60049315/74155842-835a9f80-4c15-11ea-863e-7ef814fc613d.jpg)

**Comment by buddyqc69** [comment]
Zone, quêtes ou liens wowhead vers le pnj en question et ou la quêtes incluant? Svp merci

**Comment by Lyhannor** [comment]
cela lefait pour presque tout le mod

**Comment by buddyqc69** [comment]
peut importe la créature que vous tuer cela fais ce message d'erreur ?

**Comment by Lyhannor** [comment]
pas tout le temps

**Comment by Lyhannor** [comment]
enfait sa le fait sur tout le créature mais de temps en temps 
mais la ou sa le fait le plus c'est sur les créature de quete ou il faut ramasser des objet 
car pour le jeu l'item que l'on ramase a la meme id donc il on du compier coller le mod

**Comment by buddyqc69** [comment]
Pouvez-vous vérifier si le problème existe encore ? nous avons appliquer un fix pour ce genre de problème et nous aurions besoin que vous le testié, merci !
